# Site settings
title: UP4MOVEMENT
email: up4movement@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Private fitness studio in the heart of Michigan City, Indiana

baseurl: '' # the subpath of your site, e.g. /blog/
url: '' # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: williampj

# Build settings
markdown: kramdown
# paginate: 4
# paginate_path: 'blog/page:num'
